export enum PartCategory {
    BODY_PANEL = "BODY_PANEL",
    STRUCTURAL = "STRUCTURAL",
    LIGHTING = "LIGHTING",
    GLASS = "GLASS",
    COOLING = "COOLING",
    MECHANICAL = "MECHANICAL",
    ELECTRONICS = "ELECTRONICS",
    INTERIOR_SAFETY = "INTERIOR_SAFETY"
}