export enum PartPosition {
    FRONT_BUMPER = "FRONT_BUMPER",
    REAR_BUMPER = "REAR_BUMPER",
  
    FRONT_LEFT_FENDER = "FRONT_LEFT_FENDER",
    FRONT_RIGHT_FENDER = "FRONT_RIGHT_FENDER",
    REAR_LEFT_FENDER = "REAR_LEFT_FENDER",
    REAR_RIGHT_FENDER = "REAR_RIGHT_FENDER",
  
    HOOD = "HOOD",
    TRUNK = "TRUNK",
  
    FRONT_LEFT_DOOR = "FRONT_LEFT_DOOR",
    FRONT_RIGHT_DOOR = "FRONT_RIGHT_DOOR",
    REAR_LEFT_DOOR = "REAR_LEFT_DOOR",
    REAR_RIGHT_DOOR = "REAR_RIGHT_DOOR",
  
    ROOF = "ROOF",
    QUARTER_PANEL_LEFT = "QUARTER_PANEL_LEFT",
    QUARTER_PANEL_RIGHT = "QUARTER_PANEL_RIGHT",
  
    GRILLE = "GRILLE",
    HEADLIGHT_LEFT = "HEADLIGHT_LEFT",
    HEADLIGHT_RIGHT = "HEADLIGHT_RIGHT",
    TAILLIGHT_LEFT = "TAILLIGHT_LEFT",
    TAILLIGHT_RIGHT = "TAILLIGHT_RIGHT",
  
    MIRROR_LEFT = "MIRROR_LEFT",
    MIRROR_RIGHT = "MIRROR_RIGHT",
  
    WINDSHIELD = "WINDSHIELD",
    REAR_WINDOW = "REAR_WINDOW",
    SIDE_WINDOW_LEFT = "SIDE_WINDOW_LEFT",
    SIDE_WINDOW_RIGHT = "SIDE_WINDOW_RIGHT",
  
    DOOR_HANDLE_LEFT = "DOOR_HANDLE_LEFT",
    DOOR_HANDLE_RIGHT = "DOOR_HANDLE_RIGHT",
  
    FENDER_LINER_LEFT = "FENDER_LINER_LEFT",
    FENDER_LINER_RIGHT = "FENDER_LINER_RIGHT",
  
    OTHER = "OTHER"
  }
  